name: Integration tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read
  statuses: write
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  security-events: none

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm install
      - run: npm run build
      - run: npm run test:unit:coverage
      - run: npm run test:unit:frontend:coverage

      - name: Start containers
        run: docker-compose -f "docker-compose.base.yml" -f "docker-compose.functional.yml" up -d

      - run: npm run test:integration:coverage
      - run: npm run test:coverage:merge
      - name: Publish coverage to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.base.yml" -f "docker-compose.functional.yml" down
