name: Lint
on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read
  statuses: write
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  security-events: none

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm install
      - run: npm run lint
